AllCops:
  TargetRubyVersion: 3.2

Style:
  Enabled: false
Metrics:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false
Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true
Layout/LineLength:
  Max: 140
Naming/MethodParameterName:
  Enabled: false
